
services:

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: fccpd
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: fccpd
      DB_USER: root
      DB_PASSWORD: admin123
    command: uvicorn app.main:app --host 0.0.0.0
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
      
networks:
  app-network:

volumes:
  db_data:
